#!/bin/bash
#
# Pidan - A Git helper
# Should work on sh, dash, bash, ksh, zsh
#
# Copyright (C) 2023-present, Implemented by Bin Hua <https://binhua.org/pidan>

# Define download URLs
URL1="https://res.binhua.org/dl/pidan/pidan"
URL2="https://pidan.hua.info/pidan"

# color
green(){
    echo -e "\033[32m\033[01m$1\033[0m"
}

red(){
    echo -e "\033[31m\033[01m$1\033[0m"
}

yellow(){
    echo -e "\033[33m\033[01m$1\033[0m"
}

white(){
    echo -e "\033[37m\033[01m$1\033[0m"
}

blue(){
    echo -e "\033[34m\033[01m$1\033[0m"
}

# root
if [ "$(id -u)" -ne 0 ]; then
  red "Please run this script as the root user."
  exit 1
fi

# Download and save to a temporary folder.
TMP_FILE="/tmp/pidan"

# Download via URL 1
blue "Downloading..."
if curl -o "$TMP_FILE" -fL "$URL1"; then
  green "Done"
else
  # If failed, download via URL 2
  red "Downloaded failed，try again..."
  if curl -o "$TMP_FILE" -fL "$URL2"; then
    green "Done"
  else
    red "Failed, please manually download the file from the link below and place it in /usr/local/bin.  "$URL1" or "$URL2"."
    exit 1
  fi
fi

# install to /usr/local/bin
green "Successfully"
mv "$TMP_FILE" /usr/local/bin/pidan

# Set execution permissions
chmod +x /usr/local/bin/pidan

# If successed
if [ -f /usr/local/bin/pidan ]; then
  green "Done，you can use 'pidan' now"
else
  red "Failed, you can try again"
  exit 1
fi
